In [1]:
import numpy as np
import pandas as pd

In [2]:
rng = np.random.RandomState(0)

df = pd.DataFrame(rng.randint(0,10, (3,4)), columns=['A','B','C','D'])
print(df)
print('finding exponent value of df')
exponent = np.exp(df)
print(exponent)
print('sin value of df')
sine = np.sin(df*np.pi/4)
print(sine)

   A  B  C  D
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6
finding exponent value of df
             A            B            C           D
0   148.413159     1.000000    20.085537   20.085537
1  1096.633158  8103.083928    20.085537  148.413159
2     7.389056    54.598150  1096.633158  403.428793
sin value of df
          A             B         C         D
0 -0.707107  0.000000e+00  0.707107  0.707107
1 -0.707107  7.071068e-01  0.707107 -0.707107
2  1.000000  1.224647e-16 -0.707107 -1.000000


In [3]:
#addition, subtraction, multiplication and division between two series

Name = pd.Series({'A':11, 'B':34, 'C':31}, name='Name')
Address = pd.Series({'B':43, 'A':15, 'D':51}, name='Address')
print('addition of Name and Address')
add = Name + Address
print(add)

print('subtraction between Name and Address')
sub = Name - Address
print(sub)
print('multiplication of Name and Address')
mul = Name*Address
print(mul)
print('dividing Name by Address')
division = Name/Address
print(division)

print('printing index of Name and Address')
index = Name.index | Address.index
print(index)

addition of Name and Address
A    26.0
B    77.0
C     NaN
D     NaN
dtype: float64
subtraction between Name and Address
A   -4.0
B   -9.0
C    NaN
D    NaN
dtype: float64
multiplication of Name and Address
A     165.0
B    1462.0
C       NaN
D       NaN
dtype: float64
dividing Name by Address
A    0.733333
B    0.790698
C         NaN
D         NaN
dtype: float64
printing index of Name and Address
Index(['A', 'B', 'C', 'D'], dtype='object')


In [5]:
#addition, subtraction, multiplication and division between two series using fill_value
Name = pd.Series({'A':11, 'B':34, 'C':31}, name='Name')
Address = pd.Series({'B':43, 'A':15, 'D':51}, name='Address')
print('addition of Name and Address')
add = Name.add(Address, fill_value=0)
print(add)
print('subtraction between Name and Address')
sub = Name.sub(Address, fill_value=0)
print(sub)
print('multiplication of Name and Address')
mul = Name.mul(Address, fill_value=0)
print(mul)
print('dividing Name by Address')
division = Name.div(Address, fill_value=0)
print(division)
print('printing index of Name and Address')
index = Name.index | Address.index
print(index)

addition of Name and Address
A    26.0
B    77.0
C    31.0
D    51.0
dtype: float64
subtraction between Name and Address
A    -4.0
B    -9.0
C    31.0
D   -51.0
dtype: float64
multiplication of Name and Address
A     165.0
B    1462.0
C       0.0
D       0.0
dtype: float64
dividing Name by Address
A    0.733333
B    0.790698
C         inf
D    0.000000
dtype: float64
printing index of Name and Address
Index(['A', 'B', 'C', 'D'], dtype='object')


In [6]:
#addition, subtraction, multiplication and division between two DataFrame

df1 = pd.DataFrame(rng.randint(0,10, (2,2)), columns=['A','B'])
df2 = pd.DataFrame(rng.randint(0,10, (3,3)), columns=['A','B','C'])
print('adding df1 and df2')
add = df1+df2
print(add)
print('subtraction df1 and df2')
sub = df1-df2
print(sub)

print('multiplication of df1 and df2')
mul = df1*df2
print(mul)
print('dividing df1 and df2')
div = df1/df2
print(div)
print('columns of df1 and df2')
columns = df1.columns | df2.columns
print(columns)

adding df1 and df2
      A     B   C
0  15.0  15.0 NaN
1   2.0  11.0 NaN
2   NaN   NaN NaN
subtraction df1 and df2
     A    B   C
0  1.0  1.0 NaN
1  0.0  1.0 NaN
2  NaN  NaN NaN
multiplication of df1 and df2
      A     B   C
0  56.0  56.0 NaN
1   1.0  30.0 NaN
2   NaN   NaN NaN
dividing df1 and df2
          A         B   C
0  1.142857  1.142857 NaN
1  1.000000  1.200000 NaN
2       NaN       NaN NaN
columns of df1 and df2
Index(['A', 'B', 'C'], dtype='object')


In [7]:
#addition, subtraction, multiplication and division between two DataFrame

df1 = pd.DataFrame(rng.randint(0,10, (2,2)), columns=['A','B'])
df2 = pd.DataFrame(rng.randint(0,10, (3,3)), columns=['A','B','C'])
#finding mean value of the df1 DataFrame
mean = df1.stack().mean()
print('adding df1 and df2')
add = df1.add(df2, fill_value=mean)
print(add)
print('subtraction df1 and df2')
sub = df1.add(df2, fill_value=mean)
print(sub)

print('multiplication of df1 and df2')
mul = df1.mul(df2, fill_value=mean)
print(mul)
print('dividing df1 and df2')
div = df1.div(df2, fill_value=mean)
print(div)
print('columns of df1 and df2')
columns = df1.columns | df2.columns
print(columns)

adding df1 and df2
       A     B     C
0   3.00  2.00  5.75
1  11.00  6.00  5.75
2   5.75  5.75  9.75
subtraction df1 and df2
       A     B     C
0   3.00  2.00  5.75
1  11.00  6.00  5.75
2   5.75  5.75  9.75
multiplication of df1 and df2
       A     B      C
0   0.00  0.00   8.25
1  24.00  5.00   8.25
2   8.25  8.25  19.25
dividing df1 and df2
          A         B         C
0       inf  0.000000  0.916667
1  0.375000  5.000000  0.916667
2  0.916667  0.916667  0.392857
columns of df1 and df2
Index(['A', 'B', 'C'], dtype='object')


In [8]:
#subtracting from own array
A = rng.randint(10, size=(3,4))
print(A)
print('subtracting 1st row from A')
sub = A - A[0]
print(sub)
print('printing dataframe')
df = pd.DataFrame(A, columns=list('QRST'))
print(df)
print('subtracting 1st row from df')
sub = df-df.iloc[0]
print(sub)
print('subtracting from df through column')
sub = df.sub(df['R'], axis=0)
print(sub)
print("printing 1st row's 1st and 3rd columns value")
short_df = df.iloc[0, ::2]
print(short_df)
sub_short_df = df - short_df
print(sub_short_df)

[[0 1 9 9]
 [0 4 7 3]
 [2 7 2 0]]
subtracting 1st row from A
[[ 0  0  0  0]
 [ 0  3 -2 -6]
 [ 2  6 -7 -9]]
printing dataframe
   Q  R  S  T
0  0  1  9  9
1  0  4  7  3
2  2  7  2  0
subtracting 1st row from df
   Q  R  S  T
0  0  0  0  0
1  0  3 -2 -6
2  2  6 -7 -9
subtracting from df through column
   Q  R  S  T
0 -1  0  8  8
1 -4  0  3 -1
2 -5  0 -5 -7
printing 1st row's 1st and 3rd columns value
Q    0
S    9
Name: 0, dtype: int64
     Q   R    S   T
0  0.0 NaN  0.0 NaN
1  0.0 NaN -2.0 NaN
2  2.0 NaN -7.0 NaN
